site_name: Template Documentation

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: yellow
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: yellow
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  logo: images/logo_main.jpg
  icon:
    repo: fontawesome/brands/github
  favicon: images/logo.png
  features:
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: en

nav:
  - Introduction: index.md
  - Examples:
    - Example 1: examples/example_1.md
    - Example 2: examples/example_2.md

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/antonio-d%C3%ADaz-cano-7304031b3/
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/antodiazcano